<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'View' => 'Ko\'rinish',
  '(not set)' => '(aniqlanmagan)',
  'An internal server error occurred.' => 'Server tarafda xatolik yuz berdi.',
  'Are you sure you want to delete this item?' => 'Haqiqatda ham ushbu elementni o\'chirishni hohlaysizmi?',
  'Delete' => 'O\'chirish',
  'Error' => 'Xato',
  'File upload failed.' => 'Faylni yuklab bo\'lmadi.',
  'Home' => 'Bosh sahifa',
  'Invalid data received for parameter "{param}".' => '"{param}" nign qiymati noto\'g\'ri berilgan.',
  'Login Required' => 'Kirishingiz lozim.',
  'Missing required arguments: {params}' => 'Quyidagilarning argumentlarning qiymati kiritilmagan: {params}',
  'Missing required parameters: {params}' => 'Quyidagi parametrlarning qiymati kiritilmagan: {params}',
  'No' => 'Yo\'q',
  'No help for unknown command "{command}".' => 'Справка недоступна для неизвестной команды "{command}".',
  'No help for unknown sub-command "{command}".' => 'Справка недоступна для неизвестной субкоманды "{command}".',
  'No results found.' => 'Ничего не найдено.',
  'Only files with these extensions are allowed: {extensions}.' => 'Разрешена загрузка файлов только со следующими расширениями: {extensions}.',
  'Only files with these mimeTypes are allowed: {mimeTypes}.' => 'Разрешена загрузка файлов только со следующими MIME-типами: {mimeTypes}.',
  'Page not found.' => 'Страница не найдена.',
  'Please fix the following errors:' => 'Исправьте следующие ошибки:',
  'Please upload a file.' => 'Загрузите файл.',
  'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Показаны записи <b>{begin, number}-{end, number}</b> из <b>{totalCount, number}</b>.',
  'The file "{file}" is not an image.' => 'Файл «{file}» не является изображением.',
  'The file "{file}" is too big. Its size cannot exceed {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'Файл «{file}» слишком большой. Размер не должен превышать {limit, number} {limit, plural, one{байт} few{байта} many{байт} other{байта}}.',
  'The file "{file}" is too small. Its size cannot be smaller than {limit, number} {limit, plural, one{byte} other{bytes}}.' => 'Файл «{file}» слишком маленький. Размер должен быть более {limit, number} {limit, plural, one{байт} few{байта} many{байт} other{байта}}.',
  'The format of {attribute} is invalid.' => 'Maydon qiymati formati noto\'g\'ri.',
  'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Файл «{file}» слишком большой. Высота не должна превышать {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.',
  'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Файл «{file}» слишком большой. Ширина не должна превышать {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.',
  'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Файл «{file}» слишком маленький. Высота должна быть более {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.',
  'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => 'Файл «{file}» слишком маленький. Ширина должна быть более {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.',
  'The verification code is incorrect.' => 'Неправильный проверочный код.',
  'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Всего <b>{count, number}</b> {count, plural, one{запись} few{записи} many{записей} other{записи}}.',
  'Unable to verify your data submission.' => 'Не удалось проверить переданные данные.',
  'Unknown command "{command}".' => 'Неизвестная команда "{command}".',
  'Unknown option: --{name}' => 'Неизвестная опция: --{name}',
  'Update' => 'Редактировать',
  'Yes' => 'Да',
  'You are not allowed to perform this action.' => 'Вам не разрешено производить данное действие.',
  'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Вы не можете загружать более {limit, number} {limit, plural, one{файла} few{файлов} many{файлов} other{файла}}.',
  'the input value' => 'введённое значение',
  '{attribute} "{value}" has already been taken.' => 'Siz kiritgan qiymatdan foydalanilgan.',
  '{attribute} cannot be blank.' => 'Maydonga ma\'lumot kiritilmagan.',
  '{attribute} is invalid.' => 'Kiritilgan qiymat noto\'g\'ri',
  '{attribute} is not a valid URL.' => 'Значение «{attribute}» не является правильным URL.',
  '{attribute} is not a valid email address.' => 'Значение «{attribute}» не является правильным email адресом.',
  '{attribute} must be "{requiredValue}".' => 'Значение «{attribute}» должно быть равно «{requiredValue}».',
  '{attribute} must be a number.' => 'Maydon qiymati faqat son bo\'lishi kerak.',
  '{attribute} must be a string.' => 'Значение «{attribute}» должно быть строкой.',
  '{attribute} must be an integer.' => 'Maydon qiymati butun son bo\'lishi kerak.',
  '{attribute} must be either "{true}" or "{false}".' => 'Значение «{attribute}» должно быть равно «{true}» или «{false}».',
  '{attribute} must be greater than "{compareValue}".' => 'Значение «{attribute}» должно быть больше значения «{compareValue}».',
  '{attribute} must be greater than or equal to "{compareValue}".' => 'Значение «{attribute}» должно быть больше или равно значения «{compareValue}».',
  '{attribute} must be less than "{compareValue}".' => 'Значение «{attribute}» должно быть меньше значения «{compareValue}».',
  '{attribute} must be less than or equal to "{compareValue}".' => 'Maydon qiymati {compareValue} dan kichik yoki teng bo\'lishi lozim.',
  '{attribute} must be no greater than {max}.' => 'Maydon qiymati ko\'pi bilan {max} bo\'lishi mumkin.',
  '{attribute} must be no less than {min}.' => 'Maydon qiymati kamida {min} ga teng bo\'lishi mumkin.',
  '{attribute} must be repeated exactly.' => 'Parol takroran noto\'g\'ri kiritilgan.',
  '{attribute} must not be equal to "{compareValue}".' => 'Значение «{attribute}» не должно быть равно «{compareValue}».',
  '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => 'Maydon kamida {min, number} ta belgidan iborat bo\'lishi lozim.',
  '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => 'Maydon ko\'pi bilan {max, number} ta belgidan iborat bo\'lishi lozim',
  '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => 'Значение «{attribute}» должно содержать {length, number} {length, plural, one{символ} few{символа} many{символов} other{символа}}.',
);
