<?php

namespace app\controllers;

use app\components\Controller;
use Yii;

/**
 * Class SiteController
 * @package app\controllers
 *
 */
class SiteController extends Controller
{
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $this->view->title = t("Bosh sahifa");
        $this->registerMetaTagHomePage();
        return $this->render('index');
    }

    public function actionBlogs()
    {
        return $this->render('blogs');
    }

    public function actionTopics()
    {
        return $this->render('blogs');
    }

    public function actionNews()
    {
        return $this->render('blogs');
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionContact()
    {
        return $this->renderContent('contact');
    }

    private function registerMetaTagHomePage()
    {
        Yii::$app->view->registerMetaTag([
            'name' => 'keyword',
            'content' => t("shaxsiy blog, web dasturlash, opensource developer"),
        ]);

        Yii::$app->view->registerMetaTag([
            'name' => 'description',
            'content' => t("shaxsiy blog, web dasturlash"),
        ]);
    }
}
