<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 21.11.2019
 * Time: 21:44
 */

namespace app\components;

/**
 * Class AccessControl
 * @package app\components
 */
class AccessControl extends \yii\filters\AccessControl
{
    public $rules = [];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action);
    }
}