<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 18.11.2019
 * Time: 20:59
 */

namespace app\components;

use Yii;
use yii\web\NotFoundHttpException;
use app\widgets\ActiveForm;
use yii\web\Response;

/**
 * Class ActiveRecord
 * @package app\components
 */
class ActiveRecord extends \yii\db\ActiveRecord
{

    /**
     * Yii2 dagi xatolikni to'g'rilaydi.
     * PK=id bo'lgan holatdagi faqat int sonlarni o'tkazadi
     * aks holda 404
     *
     * @param $condition
     * @return null|\yii\db\ActiveRecord
     * @throws NotFoundHttpException
     */
    public static function findOne($condition)
    {
        if (filter_var($condition, FILTER_VALIDATE_INT) === false)
            throw new NotFoundHttpException();

        return parent::findOne($condition); // TODO: Change the autogenerated stub
    }

    /**
     * Agar kelayotgan request AJAX bo'lsa,
     * ushbu modelga yuklab validatsiyadan o'tkazadi va
     * clientga jo'natadi.
     *
     * Qo'llanishi:
     * $model->ajaxValidation()
     *
     * @throws NotFoundHttpException Ahar ma'lumotlar yuklanishda xatolik yuz bersa
     * @throws \yii\base\ExitException
     */
    public function ajaxValidation()
    {
        if (!Yii::$app->request->isPost)
            return;

        if (!Yii::$app->request->isAjax)
            return;

        //Bu, PJAX formalarda uchun kerak
        //shu holatda, postValidation ishlaydi
        if (Yii::$app->request->isPjax)
            return;

        if (!$this->load(Yii::$app->request->post())) {
            throw new NotFoundHttpException();
        }

        $response = Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $result = ActiveForm::validate($this);
        if ($result !== null) {
            $response->data = $result;
        }

        Yii::$app->end();
    }

    /**
     * Agar kelayotgan request POST bo'lsa
     * ushbu modelga yuklab validatsiyadan o'tkazadi
     * Agar hammasi to'g'ri bo'lsa TRUE aks holda FALSE qaytaradi.
     *
     * @return bool
     * @throws NotFoundHttpException
     */
    public function postValidation()
    {
        if (!Yii::$app->request->isPost)
            return false;

        if (!$this->load(Yii::$app->request->post()))
            throw new NotFoundHttpException();

        return $this->validate();
    }
}