<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 17.11.2019
 * Time: 17:49
 */

namespace app\components;

/**
 * Class UrlManager
 * @package app\components
 */
class UrlManager extends \yii\web\UrlManager
{
    public function createUrl($params)
    {
        return parent::createUrl($params); // TODO: Change the autogenerated stub
    }
}