<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 19.11.2019
 * Time: 19:49
 */

namespace app\widgets;


use yii\base\Widget;

/**
 * Class FooterWidget
 * @package app\widgets
 */
class FooterWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('footer');
    }
}