<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 17.11.2019
 * Time: 17:53
 */

namespace app\widgets;

use Yii;
use yii\base\Widget;

/**
 * Class LangWidget
 * @package app\widgets
 */
class LangWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run() {
        return $this->render('lang', [
            'current' => Yii::$app->language,
            'langs' => Yii::$app->params['languages'],
        ]);
    }
}