<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 17.11.2019
 * Time: 18:11
 */

namespace app\widgets;

use Yii;
use yii\base\Widget;

/**
 * Class MenuWidget
 * @package app\widgets
 */
class MenuWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $current_route = Yii::$app->controller->id."/".Yii::$app->controller->action->id;

        return $this->render("menu",[
            "menus" => self::getMenus(),
            "current_route" => $current_route,
        ]);
    }

    private static function getMenus()
    {
        return
            [
                [
                    "title" => Yii::$app->name,
                    "icon" => "<i class='fa fa-newspaper'></i>",
                    "url" => ["site/index"],
                ],
                [
                    "title" => t("Maqolalar"),
                    "icon" => "<i class='fa fa-comment'></i>",
                    "url" => ["articles/index"],
                ],
                [
                    "title" => t("Yangiliklar"),
                    "icon" => "<i class='fa fa-comment'></i>",
                    "url" => ["news/index"],
                ],
                [
                    "title" => t("Bloglar"),
                    "icon" => "<i class='fa fa-newspaper'></i>",
                    "url" => ["blogs/index"],
                ],
                [
                    "title" => t("Sayt haqida"),
                    "icon" => "<i class='fa fa-info-circle'></i>",
                    "url" => ["site/about"],
                ],
                [
                    "title" => t("Aloqa"),
                    "icon" => "<i class='fa fa-address-book'></i>",
                    "url" => ["site/contact"],
                ],
            ];
    }
}