<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 19.11.2019
 * Time: 19:59
 */

namespace app\widgets;


use app\models\UserArticlesModel;
use yii\base\Widget;

/**
 * Class TopArticlesWidget
 * @package app\widgets
 */
class TopArticlesWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $list = UserArticlesModel::find()
            ->orderBy(['id' => SORT_ASC])
            ->all();
        return $this->render('top-articles',[
            'list' => $list,
        ]);
    }
}