<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 19.11.2019
 * Time: 20:02
 */

namespace app\widgets;


use app\models\UserTagsModel;
use yii\base\Widget;

/**
 * Class TopTagsWidget
 * @package app\widgets
 */
class TopTagsWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $list = UserTagsModel::find()
            ->orderBy(['id' => SORT_ASC])
            ->all();
        return $this->render('top-tags',[
            'list' => $list,
        ]);
    }
}