<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 21.11.2019
 * Time: 20:33
 */

namespace app\models;


use app\components\ActiveRecord;
use yii\helpers\Inflector;

/**
* Class UserTagsModel
* @package app\models
* @property $user_id
* @property $name
* @property $slug
* @property $created_at
* @property $updated_at
*/
class UserTagsModel extends ActiveRecord
{
    const SCENARIO_ADD = 'add';

    public static function tableName()
    {
        return 'tr_user_tags';
    }

    public function scenarios()
    {
        return [
            self::SCENARIO_ADD => ['user_id', 'name', 'slug']
        ];
    }

    public function rules()
    {
        return [
            [['name'], 'required',
                'on' => [self::SCENARIO_ADD]],
            [['name'],'string', 'length' => [2,30],
                'on' => [self::SCENARIO_ADD]],
        ];
    }

    public function beforeSave($insert)
    {
        $this->slug = Inflector::slug($this->name);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}