<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 21.11.2019
 * Time: 20:32
 */

namespace app\models;

use Yii;
use app\components\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\Inflector;
use yii\helpers\Json;

/**
* Class UserArticlesModel
* @package app\models
* @property $user_id
* @property $blog_id
* @property $tag_id
* @property $title
* @property $content
* @property $image
* @property $slug
* @property $count_vote_up
* @property $count_vote_down
* @property $count_read
* @property $count_comment
* @property $status
* @property $created_at
* @property $updated_at
* @property $contentCut
*/
class UserArticlesModel extends ActiveRecord
{
    const SCENARIO_EDIT = 'edit';

    public static function tableName()
    {
        return 'tr_user_articles';
    }

    public function attributeLabels()
    {
        return [
            'blog_id' => t("Blog"),
            'tag_id' => t("Teg"),
            'title' => t("Mavzu"),
            "content" => t("Maqola matni"),
            "image" => t("Rasm"),
        ];
    }
    public function scenarios()
    {
        return [
            self::SCENARIO_EDIT => ['user_id', 'blog_id', 'tag_id', 'title', 'content', 'image', 'slug'],
        ];
    }

    public function rules()
    {
        return [
            [['blog_id', 'title', 'content', 'tag_id'],'required',
                'on' => [self::SCENARIO_EDIT]],
            [['blog_id'],'each',
                'rule' => [
                    'exist', 'targetClass' => UserBlogsModel::class,
                    'targetAttribute' =>  'id',
                ], 'on'=>[self::SCENARIO_EDIT]],
            [["image"], 'file', 'skipOnEmpty' => true,
                "extensions" => "png, jpg, jpeg",
                'on' => [self::SCENARIO_EDIT]],
        ];
    }

    public function beforeSave($insert)
    {
        $tags = ArrayHelper::map(UserTagsModel::find()
            ->all(),'id', 'name');
        if($this->tag_id)
        {
            $tag_id = $this->tag_id;
            foreach ($tag_id as $key => $value)
            {
                if(!isset($tags[$value]))
                {
                    $model = new UserTagsModel();
                    $model->user_id = Yii::$app->user->id;
                    $model->setScenario($model::SCENARIO_ADD);
                    $model->name = $value;
                    if($model->save())
                        $tag_id[$key] = $model->id;
                }
            }
            $this->tag_id = $tag_id;
        }

        $this->blog_id = Json::encode($this->blog_id);
        $this->tag_id = Json::encode($this->tag_id);
        $this->slug = Inflector::slug($this->title);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->blog_id = Json::decode($this->blog_id);
        $this->tag_id = Json::decode($this->tag_id);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function getContentCut()
    {
        $content = explode('&lt;cut&gt;', $this->content);
        return $content[0]?? "";
    }
}