<?php
/**
 *
 * Created by PhpStorm.
 * User: Rozmetov Jasur ( @rozmetovjasur )
 * Date: 01.12.2019
 * Time: 19:03
 */

namespace app\models;


use app\components\ActiveRecord;
use Yii;
use yii\helpers\Json;

/**
* Class UserNewsModel
* @package app\models
* @property $user_id
* @property $category_id
* @property $title
* @property $content
* @property $image
* @property $slug
* @property $keywords
* @property $description
* @property $count_vote_up
* @property $count_vote_down
* @property $count_read
* @property $count_comment
* @property $status
* @property $created_at
* @property $updated_at
* @property $contentCut
* @property \app\models\UsersModel $user
*/
class UserNewsModel extends ActiveRecord
{
    public static function tableName()
    {
        return 'tr_user_news';
    }


    public function afterFind()
    {
        $this->category_id = Json::decode($this->category_id);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function getContentCut()
    {
        $content = explode('&lt;cut&gt;', $this->content);
        return $content[0]?? "";
    }

    public function getUser()
    {
        return $this->hasOne(UsersModel::class,['id' => 'user_id']);
    }

    /**
     * @return string
     * @throws \yii\base\InvalidConfigException
     */
    public function getCreatedAt()
    {
        return Yii::$app->formatter->asDatetime($this->created_at);
    }
}